---
name: Schedule - Link Checker

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.0
        id: lychee
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}


      - name: Find the last open report issue
        id: last-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            link-checker

      - name: Update last updated report issue
        # if: ${{ steps.last-issue.outputs.has-found == 'true' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Broken links detected in docs ðŸ”—
          content-filepath: ./lychee/out.md
          # Update an existing issue if one was found (issue-number),
          # otherwise an empty value creates a new issue:
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          # Add a label(s) that `last-issue` can use to find this issue,
          # and any other relevant labels for the issue itself:
          labels: |
            link-checker
