---
name: "Comment BOT"

# concurrency:
#   group: ${{ github.ref }}-${{ github.workflow }}
#   cancel-in-progress: true

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]


jobs:

  call-bot:
    name: Dispatcher
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.html_url, '/pull/')  }}
    uses: .github/workflows/_bot-activities.yml
    secrets: inherit
